### ISSUE TITLE
Sometimes shows analysis, sometimes doesn't.

### ISSUE THREAD

**Issue by Samhain-III** [nathancarter/vg-match-analysis#1]
I'm not familiar with coding but I can try describing the problem.

Sometimes when you press "Go" for a certain match, you go to a page saying "This page is empty and sad..." etc. However, when you go back some time later, it works! Then you go back again maybe in an hour or so, and you get the same error message. This happened when I accessed it on a Samsung tablet, if that matters.

**Comment by nathancarter** [comment]
Thanks for the report!  I think it may have something to do with traffic, but I'm not 100% sure.  I'm going to start digging into the errors today/tomorrow if I can to sort this out.  You're not the only one with the problem.  Thanks for reporting, and I'll report back here with progress on the issue.

**Comment by nathancarter** [comment]
I think I just tracked this down and fixed it in [the last commit](https://github.com/nathancarter/vg-match-analysis/commit/291ebf71c7d261bd16b7971c028fd096c714c3be).  Thanks for the report!
