### ISSUE TITLE
Empty and Sad error

### ISSUE THREAD

**Issue by nicoleigasu** [nathancarter/vg-match-analysis#2]
http://vgu.herokuapp.com/analysis.html?ign=NicleIgasu&shard=EU&match=e50fcdf2-2fd7-11e7-96df-02fd63b150ad

When I tried to go to the analysis for my latest match I got an "Empty and Sad" page (see link above). I tried refreshing and going back a few times but it didn't work. 

There's this guy with IGN Selial who was on my team in that match. He played Baptiste, but the picture of this hero isn't showing. It's just an empty white square. When I searched up Selial, I discovered that all of his matches lead to the "Empty and Sad" page. 

I'm using safari on my iPhone in case that's relevant information.

**Comment by nicoleigasu** [comment]
Same problem with this match: http://vgu.herokuapp.com/analysis.html?ign=NicleIgasu&shard=EU&match=7b24d1b4-3025-11e7-96df-02fd63b150ad

**Comment by nicoleigasu** [comment]
With the match above it is the player with IGN "masturbasn" who's hero picture isn't shown, who was again one of my team. 

(Region = EU)

**Comment by nathancarter** [comment]
Thank you very much for the report.  I hadn't updated the app since 2.4, and so it wasn't ready to handle Baptiste matches.  Fixed it just now!
