### ISSUE TITLE
Dr. Kestrel thinks Coat of Plates has more armor than Metal Jacket

### ISSUE THREAD

**Issue by matefh** [nathancarter/vg-match-analysis#3]
Example: http://vgu.herokuapp.com/analysis.html?ign=matefh&shard=EU&match=a7f3f040-3529-11e7-b126-02fd63b150ad

**Weapon Power**:
Samuel's Serpent Mask
Samuel's Sorrowblade
Samuel's Tornado Trigger
Samuel's Tension Bow

**Armor**:
*Gwen's Metal Jacket (though Coat of Plates is better)*
Gwen's Aegis (which has a little armor, but Coat of Plates is much better)

**Comment by nathancarter** [comment]
Whoops -- I always get those two mixed up.  Will look into it today.  Thanks!

**Comment by nathancarter** [comment]
Fixed and pushed to production.  Thanks!
https://github.com/nathancarter/vg-match-analysis/commit/b0bf78c8a785bb73b75bebf9acb4f6eb6060111b
