### ISSUE TITLE
Empty and Sad

### ISSUE THREAD

**Issue by StefanWerW** [nathancarter/vg-match-analysis#4]
Error on loading page: http://vgu.herokuapp.com/analysis.html?ign=Chulepa&shard=EU&match=1e5a4e80-48c8-11e7-bc3e-02fd63b150ad

Empty and Sad

Oops. I wish this website were perfect, but it turns out we've hit an error. Feel free to report it using the GitHub link at the bottom of the page.

**Comment by nathancarter** [comment]
Thanks for the report!  Just fixed this bug and pushed the change to production.  I appreciate your taking the time to submit and help me find the error.
